'use client';

import { useEffect, useState } from 'react';
import { Loader2Icon } from 'lucide-react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { createClient } from '@/utils/supabase/client';

interface EnrollMFAProps {
  onEnrolled: () => void;
  onCancelled: () => void;
}

export function EnrollMFA({ onEnrolled, onCancelled }: EnrollMFAProps) {
  const supabase = createClient();

  const [factorId, setFactorId] = useState('');
  const [qr, setQR] = useState('');
  const [secret, setSecret] = useState('');
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    (async () => {
      const { data, error: enrollError } = await supabase.auth.mfa.enroll({
        factorType: 'totp'
      });
      if (enrollError) {
        setError(enrollError.message);
        setLoading(false);
        return;
      }
      setFactorId(data.id);
      setQR(data.totp.qr_code);
      setSecret(data.totp.secret);
      setLoading(false);
    })();
  }, [supabase]);

  const handleEnable = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSubmitting(true);
    try {
      const { data: challenge, error: challengeError } =
        await supabase.auth.mfa.challenge({ factorId });
      if (challengeError) {
        throw challengeError;
      }

      const { error: verifyError } = await supabase.auth.mfa.verify({
        factorId,
        challengeId: challenge.id,
        code
      });
      if (verifyError) {
        throw verifyError;
      }

      toast.success('Two-factor authentication enabled');
      onEnrolled();
    } catch (err) {
      const message =
        err instanceof Error ? err.message : 'Unable to enable two-factor auth';
      setError(message);
      toast.error(message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="grid gap-5">
      {error && (
        <div className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">
          {error}
        </div>
      )}

      <div className="grid gap-2 text-sm text-muted-foreground">
        <p>
          1. Scan the QR code below with your authenticator app (e.g. Google
          Authenticator, 1Password, Authy).
        </p>
        <p>
          2. If you cannot scan the code, manually enter the secret key into
          your authenticator app.
        </p>
        <p>3. Enter the 6-digit code generated by the app to confirm.</p>
      </div>

      <div className="flex justify-center">
        {loading ? (
          <div className="flex h-48 w-48 items-center justify-center">
            <Loader2Icon className="size-8 animate-spin text-muted-foreground" />
          </div>
        ) : qr ? (
          // The QR code is an SVG data URL returned by Supabase Auth.
          <img
            src={qr}
            alt="QR code to scan with your authenticator app"
            className="h-48 w-48 rounded-lg border"
          />
        ) : (
          <div className="flex h-48 w-48 items-center justify-center rounded-lg border text-sm text-muted-foreground">
            QR unavailable
          </div>
        )}
      </div>

      <div className="grid gap-2">
        <Label htmlFor="secret" className="text-muted-foreground">
          Secret key (manual entry)
        </Label>
        <Input
          id="secret"
          readOnly
          value={secret}
          onFocus={e => e.target.select()}
          className="font-mono text-center text-sm tracking-widest"
        />
      </div>

      <form onSubmit={handleEnable} className="grid gap-4">
        <div className="grid gap-2">
          <Label htmlFor="code">Verification code</Label>
          <Input
            id="code"
            inputMode="numeric"
            autoComplete="one-time-code"
            placeholder="000000"
            maxLength={6}
            value={code}
            onChange={e => setCode(e.target.value.trim())}
            disabled={submitting}
            className="text-center text-lg tracking-[0.5em]"
          />
        </div>
        <div className="flex gap-3">
          <Button
            type="submit"
            className="flex-1"
            disabled={submitting || code.length < 6}
          >
            {submitting ? (
              <>
                <Loader2Icon className="animate-spin" />
                Verifying...
              </>
            ) : (
              'Verify & Enable'
            )}
          </Button>
          <Button
            type="button"
            variant="outline"
            onClick={onCancelled}
            disabled={submitting}
          >
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}
