image:
  repository: curlimages/curl
  tag: latest

# Optional: set namespace here (leave empty to use the Helm release namespace)
namespace: "fieldglass-cron"

cronjob:
  schedule: "0 0 * * *"
  apiUrl: "https://fieldglass-app.damingerdai.com//api/cron"
  # 部署时通过 --set cronjob.cronSecret=xxx 覆盖
  cronSecret: "default-placeholder-token"